"""empty message

Revision ID: 09c08ca0df10
Revises: d6c3a5e4555c
Create Date: 2024-06-18 09:24:48.803818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c08ca0df10'
down_revision = 'd6c3a5e4555c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('countdown', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic', schema=None) as batch_op:
        batch_op.drop_column('countdown')

    # ### end Alembic commands ###
