"""empty message

Revision ID: 191d1bcfb968
Revises: d15da7522060
Create Date: 2024-09-06 17:44:24.375222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191d1bcfb968'
down_revision = 'd15da7522060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_template', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
