"""empty message

Revision ID: 1dd820345a52
Revises: b34393c60a74
Create Date: 2024-08-03 05:56:27.905787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd820345a52'
down_revision = 'b34393c60a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letter', sa.String(length=1000000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticer', schema=None) as batch_op:
        batch_op.drop_column('letter')

    # ### end Alembic commands ###
