"""empty message

Revision ID: 296e8597229b
Revises: bd22290a8b47
Create Date: 2026-02-03 18:28:11.002047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296e8597229b'
down_revision = 'bd22290a8b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=400), nullable=True))
        batch_op.drop_column('parent_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_phone', sa.VARCHAR(length=400), nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
