"""empty message

Revision ID: 2ae923824941
Revises: b613c2da627c
Create Date: 2024-04-25 19:26:09.050831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae923824941'
down_revision = 'b613c2da627c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_class_name', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.drop_column('original_class_name')

    # ### end Alembic commands ###
