"""empty message

Revision ID: 316b99244896
Revises: 73da2a55b6fb
Create Date: 2024-05-29 10:38:45.876114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316b99244896'
down_revision = '73da2a55b6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sba', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sba', schema=None) as batch_op:
        batch_op.drop_column('percentage')

    # ### end Alembic commands ###
