"""empty message

Revision ID: 3c9797818f13
Revises: 92e68dd01af3
Create Date: 2024-04-12 17:20:13.996087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9797818f13'
down_revision = '92e68dd01af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remark', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
