"""empty message

Revision ID: 3d7c23164603
Revises: c7b6c8759de2
Create Date: 2024-05-01 20:41:17.309977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7c23164603'
down_revision = 'c7b6c8759de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rank', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('subject_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('remark', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('term', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('class_score', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('total', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('exams_score', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('pos', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('all_total', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('change_request', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='grading_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='grading_pkey')
    )
    # ### end Alembic commands ###
