"""empty message

Revision ID: 53d9af60b5d8
Revises: f3cdaf452d3f
Create Date: 2024-05-07 13:38:27.916020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d9af60b5d8'
down_revision = 'f3cdaf452d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
