"""empty message

Revision ID: 57e0d42d0cde
Revises: e0d727823a4b
Create Date: 2024-04-16 08:06:22.472441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e0d42d0cde'
down_revision = 'e0d727823a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_remark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_remark', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
