"""empty message

Revision ID: 6bdcec8ed86a
Revises: 3e4a6f50cf56
Create Date: 2024-08-02 11:55:36.819963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdcec8ed86a'
down_revision = '3e4a6f50cf56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticer', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=100000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticer', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=100000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
