"""empty message

Revision ID: 6fc306a1b897
Revises: c94b13ad4fad
Create Date: 2024-04-22 12:41:20.518055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc306a1b897'
down_revision = 'c94b13ad4fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.drop_column('term')

    # ### end Alembic commands ###
