"""empty message

Revision ID: 73da2a55b6fb
Revises: 23c130fbb188
Create Date: 2024-05-28 13:31:12.787899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73da2a55b6fb'
down_revision = '23c130fbb188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pend_grade')
    op.drop_table('notice')
    op.drop_table('exam_attendance')
    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owop', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('history', sa.String(length=400), nullable=True))

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_together', sa.String(length=400), nullable=True))

    with op.batch_alter_table('signature', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.drop_column('grade_together')

    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.drop_column('history')
        batch_op.drop_column('owop')

    op.create_table('exam_attendance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('subject_name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('exam_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='exam_attendance_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exam_attendance_pkey')
    )
    op.create_table('notice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='notice_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notice_pkey')
    )
    op.create_table('pend_grade',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('term', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('class_score', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('total', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('exams_score', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('grade_id', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('staff_number', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='pend_grade_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pend_grade_pkey')
    )
    # ### end Alembic commands ###
