"""empty message

Revision ID: 760100d0afb5
Revises: 3d7c23164603
Create Date: 2024-05-02 04:02:04.817965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760100d0afb5'
down_revision = '3d7c23164603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_setup')
    op.drop_table('broad_sheet')
    op.drop_table('remark')
    op.drop_table('grading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rank', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('subject_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('remark', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('term', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('class_score', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('total', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('exams_score', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('pos', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('all_total', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('change_request', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='grading_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='grading_pkey')
    )
    op.create_table('remark',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_remark', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('attitude', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('interest', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('attendance', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('class_term', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='remark_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='remark_pkey')
    )
    op.create_table('broad_sheet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('english', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('math', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('science', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('socialstudies', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('ghanalanguage', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('creativeart', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('social', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('rme', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('careertech', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('pos', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('all_total', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('computing', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('french', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('term', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('original_class_name', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='broad_sheet_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='broad_sheet_pkey')
    )
    op.create_table('mail_setup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('working_mail', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('push_notification', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('bulk_message', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('school_name', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='mail_setup_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mail_setup_pkey')
    )
    # ### end Alembic commands ###
