"""empty message

Revision ID: 77abc459a351
Revises: fa46ed86d4be
Create Date: 2024-09-30 16:28:56.125336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77abc459a351'
down_revision = 'fa46ed86d4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_on', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees_type', schema=None) as batch_op:
        batch_op.drop_column('show_on')

    # ### end Alembic commands ###
