"""empty message

Revision ID: 812199f9206c
Revises: 4f3b1997a33b
Create Date: 2024-04-19 13:22:57.054548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812199f9206c'
down_revision = '4f3b1997a33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
