"""empty message

Revision ID: 92e68dd01af3
Revises: cbf9ff83acf8
Create Date: 2024-04-11 19:02:26.849455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e68dd01af3'
down_revision = 'cbf9ff83acf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_master', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('for_class', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('for_class')
        batch_op.drop_column('form_master')

    # ### end Alembic commands ###
