"""empty message

Revision ID: 9305f1964ee8
Revises: 7c4689654a05
Create Date: 2024-05-06 18:24:52.520414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9305f1964ee8'
down_revision = '7c4689654a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('don', sa.String(length=400), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_number', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('admission_number')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('don')

    # ### end Alembic commands ###
