"""empty message

Revision ID: 9c340c8851fd
Revises: 
Create Date: 2024-02-27 10:42:33.404445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c340c8851fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=400), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=5000), nullable=True))
        batch_op.drop_column('phone')
        batch_op.drop_column('password')
        batch_op.drop_column('username')
        batch_op.drop_column('region')

    # ### end Alembic commands ###
