"""empty message

Revision ID: a8fc6c5ffcd3
Revises: 1dd820345a52
Create Date: 2024-08-04 21:45:35.762261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fc6c5ffcd3'
down_revision = '1dd820345a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('sub_strand',
               existing_type=sa.VARCHAR(length=1000000),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('class_name',
               existing_type=sa.VARCHAR(length=100000),
               type_=sa.String(length=400),
               existing_nullable=True)
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
        batch_op.alter_column('class_name',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=100000),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
        batch_op.alter_column('sub_strand',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000000),
               existing_nullable=True)

    # ### end Alembic commands ###
