"""empty message

Revision ID: b34393c60a74
Revises: 6bdcec8ed86a
Create Date: 2024-08-02 12:48:59.068954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34393c60a74'
down_revision = '6bdcec8ed86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees_type', schema=None) as batch_op:
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###
