"""empty message

Revision ID: bd22290a8b47
Revises: 45b71a33583a
Create Date: 2024-11-25 08:57:48.727528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd22290a8b47'
down_revision = '45b71a33583a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grading', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grading', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
