"""empty message

Revision ID: be15bb55aa18
Revises: 316b99244896
Create Date: 2024-05-30 11:25:06.052237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be15bb55aa18'
down_revision = '316b99244896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.drop_column('default')

    # ### end Alembic commands ###
