"""empty message

Revision ID: c7b6c8759de2
Revises: 2ae923824941
Create Date: 2024-04-25 19:38:42.989019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b6c8759de2'
down_revision = '2ae923824941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_remark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_remark', schema=None) as batch_op:
        batch_op.drop_column('attendance')

    # ### end Alembic commands ###
