"""empty message

Revision ID: cbf9ff83acf8
Revises: ca7fb4991ab3
Create Date: 2024-04-09 17:47:11.766345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf9ff83acf8'
down_revision = 'ca7fb4991ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=400), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('gender')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
