"""empty message

Revision ID: ce7a0fcc0bd9
Revises: 04c79f60cc51
Create Date: 2024-06-23 22:22:35.069936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7a0fcc0bd9'
down_revision = '04c79f60cc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.alter_column('church_logo',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.alter_column('church_logo',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
