"""empty message

Revision ID: d15da7522060
Revises: eaeff3da78e2
Create Date: 2024-09-06 15:01:00.479133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15da7522060'
down_revision = 'eaeff3da78e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=400), nullable=True),
    sa.Column('created_date', sa.String(length=400), nullable=True),
    sa.Column('school_name', sa.String(length=400), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deduction', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.drop_table('salary_template')
    # ### end Alembic commands ###
