"""empty message

Revision ID: d6c3a5e4555c
Revises: cc9f8b1a35ad
Create Date: 2024-06-12 10:15:27.069247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c3a5e4555c'
down_revision = 'cc9f8b1a35ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_status', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.drop_column('current_status')

    # ### end Alembic commands ###
