"""empty message

Revision ID: e0d727823a4b
Revises: 9bb88778c96c
Create Date: 2024-04-15 17:34:01.891135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d727823a4b'
down_revision = '9bb88778c96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_remark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_number', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_remark', schema=None) as batch_op:
        batch_op.drop_column('student_number')

    # ### end Alembic commands ###
