"""empty message

Revision ID: eaeff3da78e2
Revises: a8fc6c5ffcd3
Create Date: 2024-08-17 15:29:52.993382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaeff3da78e2'
down_revision = 'a8fc6c5ffcd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=500), nullable=True),
    sa.Column('class_name', sa.String(length=400), nullable=True),
    sa.Column('school_name', sa.String(length=400), nullable=True),
    sa.Column('date', sa.String(length=400), nullable=True),
    sa.Column('image', sa.String(length=1000000), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    # ### end Alembic commands ###
