"""empty message

Revision ID: f033dc9edf71
Revises: 191d1bcfb968
Create Date: 2024-09-08 14:01:45.553326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f033dc9edf71'
down_revision = '191d1bcfb968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.String(length=400), nullable=True),
    sa.Column('created_date', sa.String(length=400), nullable=True),
    sa.Column('school_name', sa.String(length=400), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_salary', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_template', schema=None) as batch_op:
        batch_op.drop_column('net_salary')

    op.drop_table('allowance')
    # ### end Alembic commands ###
