"""empty message

Revision ID: f073251643a7
Revises: f204f6726945
Create Date: 2024-05-09 13:05:33.700909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f073251643a7'
down_revision = 'f204f6726945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.alter_column('english',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('math',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('science',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('socialstudies',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('ghanalanguage',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('creativeart',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('social',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('rme',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('careertech',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('computing',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('french',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broad_sheet', schema=None) as batch_op:
        batch_op.alter_column('french',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
        batch_op.alter_column('computing',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('careertech',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('rme',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=True)
        batch_op.alter_column('social',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('creativeart',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('ghanalanguage',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('socialstudies',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('science',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('math',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
        batch_op.alter_column('english',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###
