"""empty message

Revision ID: f3cdaf452d3f
Revises: 9305f1964ee8
Create Date: 2024-05-06 18:40:03.827366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cdaf452d3f'
down_revision = '9305f1964ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('n', sa.String(length=400), nullable=True))
        batch_op.drop_column('don')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('don', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
        batch_op.drop_column('n')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
