"""empty message

Revision ID: fa46ed86d4be
Revises: 5c5554f716a2
Create Date: 2024-09-28 07:32:05.422720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa46ed86d4be'
down_revision = '5c5554f716a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver', sa.String(length=400), nullable=True),
    sa.Column('message', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=400), nullable=True),
    sa.Column('created_date', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fees_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fees_amount', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('received_by', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees_payment', schema=None) as batch_op:
        batch_op.drop_column('received_by')
        batch_op.drop_column('fees_amount')

    op.drop_table('notify')
    # ### end Alembic commands ###
